--- 
backend: 
  branch: main
  name: git-gateway
  squash_merges: true
collections: 
  - 
    files: 
      - 
        editor: 
          preview: false
        fields: 
          - 
            hint: "This is used for the site title"
            label: "Site Name"
            name: sitename
            widget: string
          - 
            hint: "This is used as descriptive text for links that link to this site"
            label: "Site Description"
            name: sitedescription
            widget: string
          - 
            label: "Site Language"
            name: sitelang
            pattern: 
              - "^[a-z]{2}([-])?([A-Za-z]{2})?$"
              - "Must match \"xx\" or \"xx-XX\" syntax (ex. \"en\" or \"sv-SE\")"
            widget: string
        file: content/site/info.json
        format: json
        label: Info
        name: info
    label: "Site settings"
    name: site
  - 
    create: true
    editor: 
      preview: false
    fields: 
      - 
        label: Title
        name: title
        required: true
        widget: string
      - 
        label: "Publish Date"
        name: date
        required: true
        widget: datetime
      - 
        label: Description
        name: description
        required: false
        widget: string
      - 
        allow_multiple: false
        hint: "Images sized 1200px x 800px work best."
        label: "Cover Image"
        name: cover
        required: false
        widget: image
      - 
        label: Body
        name: body
        required: false
        widget: markdown
      - 
        field: 
          label: Image
          name: image
          widget: image
        label: Gallery
        name: gallery
        required: false
        summary: "{{fields.image}}"
        widget: list
    folder: content/blog
    format: frontmatter
    label: Blog
    name: blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  - 
    create: true
    fields: 
      - 
        default: animals
        label: "Project Category"
        name: category
        options: 
          - 
            label: Animals
            value: animals
          - 
            label: Food
            value: food
        widget: select
      - 
        label: Title
        name: title
        required: true
        widget: string
      - 
        label: Description
        name: description
        required: false
        widget: string
      - 
        allow_multiple: false
        label: "Cover Image"
        name: cover
        required: false
        widget: image
      - 
        label: Content
        name: body
        required: false
        widget: markdown
      - 
        field: 
          label: Image
          name: image
          widget: image
        label: Gallery
        name: gallery
        required: false
        summary: "{{fields.image}}"
        widget: list
    folder: content/projects
    format: frontmatter
    label: Projects
    label_singular: Project
    name: projects
    preview_path: "projects/{{slug}}"
    slug: "{{slug}}"
logo_url: "https://rmdholistics.com/icon.png"
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
site_url: "https://rmdholistics.com/"
